pipeline{
    agent any
    
    stages{
        stage('Checkout...'){
            steps{
                echo "Checkout code..."
            }
        }
        
        stage('Hello'){
            steps{                
                sh "python3 section-08-deploying-with-containers/hello.py"                
                sh """
                python3 --version
                """
            }
        }
        
        stage('TOX-Train model..'){
            steps{
                echo "running text on Section-05 Model Package"
                //sh "python section-05-production-model-package/regression_model/train_pipeline.py"
                sh """
                bash
                python3 -m virtualenv venv 
                source ~/venv/bin/activate
                python3 -m pip install --upgrade pip
                python3 -m pip install --user tox
                python3 -m install colorama
                python3 -m install appdirs
                python3 -m install -U pytest
                """ 
                sh "python3 -m tox -c section-05-production-model-package/tox.ini -e test_package"
                echo "SALIENDO text on Section-05 Model Package"
            }
        }

        stage('Deploying to prod'){
            steps{
                mvn 'clean install'
            }
        }
    }
}


